image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test

variables:
  project: "NadekoBot"
  tests: "Nadeko.Tests"

before_script:
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "src/$project"
  script:
    - "cd $build_path"
    - "dotnet build -c Release"

test:
  stage: test
  variables:
    tests_path: "src/$tests"
  script:
    - "cd $tests_path"
    - "dotnet test"