version: "3.5"
services:
  nadeko:
    build: .
    #image: kwoth/nadeko
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./data:/app/data
  redis:
    image: redis:alpine
    sysctls:
      net.core.somaxconn: 511

